import { Agent } from '@smythos/sdk';

async function main() {
  console.log('🚀 Starting Mobile DevOps Agent...');
  
  const agent = new Agent({
    name: 'Mobile DevOps Assistant',
    behavior: `Expert mobile development assistant specializing in Cordova/PhoneGap workflows. 
    Helps with Android and iOS build processes, code signing, app store deployment, and troubleshooting.`,
    model: 'gpt-4o',
  });

  // Add Mobile Development Skills
  agent.addSkill({
    name: 'CordovaConfigGenerator',
    description: 'Generate optimized Cordova config.xml for Android/iOS deployment',
    process: async ({ appName, packageId, platforms, minSdkVersion = 24 }) => {
      const configXml = `<?xml version='1.0' encoding='utf-8'?>
<widget id="${packageId}" version="1.0.0" xmlns="http://www.w3.org/ns/widgets">
    <name>${appName}</name>
    <description>Mobile app built with Cordova - Generated by Mobile DevOps MCP</description>
    
    <preference name="android-minSdkVersion" value="${minSdkVersion}" />
    <preference name="android-targetSdkVersion" value="35" />
    <preference name="AndroidWindowSplashScreenAnimatedIcon" value="res/screen/android/splash.png" />
    
    ${platforms.includes('android') ? `
    <platform name="android">
        <preference name="AndroidWindowSplashScreenAnimatedIcon" value="res/screen/android/splash.png" />
        <icon density="ldpi" src="res/icon/android/icon-36-ldpi.png" />
        <icon density="mdpi" src="res/icon/android/icon-48-mdpi.png" />
        <icon density="hdpi" src="res/icon/android/icon-72-hdpi.png" />
        <icon density="xhdpi" src="res/icon/android/icon-96-xhdpi.png" />
    </platform>` : ''}
    
    ${platforms.includes('ios') ? `
    <platform name="ios">
        <preference name="deployment-target" value="11.0" />
        <icon height="57" src="res/icon/ios/icon-57.png" width="57" />
        <icon height="114" src="res/icon/ios/icon-57-2x.png" width="114" />
        <icon height="72" src="res/icon/ios/icon-72.png" width="72" />
        <icon height="144" src="res/icon/ios/icon-72-2x.png" width="144" />
    </platform>` : ''}
    
    <access origin="*" />
</widget>`;

      return {
        config: configXml,
        message: `Generated production-ready Cordova config.xml for ${appName} targeting ${platforms.join(', ')}`,
        platforms: platforms,
        features: [
          'Optimized Android SDK versions (min: 24, target: 35)',
          'iOS deployment target: 11.0+',
          'Platform-specific splash screens and icons',
          'Universal access permissions configured'
        ]
      };
    },
  });

  agent.addSkill({
    name: 'AndroidBuildDiagnostic', 
    description: 'Analyze Android build errors and provide solutions',
    process: async ({ errorLog, gradleVersion, targetSdkVersion }) => {
      let diagnosis = [];
      let solutions = [];
      
      // Based on your real Android build experience
      if (errorLog.includes('lStar not found')) {
        diagnosis.push('Android resource compatibility issue detected');
        solutions.push('Update compileSdkVersion to 31+ and add android:exported="true" to activities');
      }
      if (errorLog.includes('Could not find method compile')) {
        diagnosis.push('Deprecated Gradle dependency syntax');
        solutions.push('Replace "compile" with "implementation" in build.gradle dependencies');
      }
      if (errorLog.includes('Build-Tools') && errorLog.includes('missing')) {
        diagnosis.push('Missing Android SDK build tools');
        solutions.push('Run "cordova requirements android" to install missing components');
      }
      if (errorLog.includes('SDK_VERSION')) {
        diagnosis.push('SDK version mismatch detected');
        solutions.push('Ensure MIN_SDK_VERSION=24 and SDK_VERSION=35 in your build configuration');
      }

      return {
        diagnosis: diagnosis.length > 0 ? diagnosis : ['No specific issues detected in log'],
        solutions: solutions.length > 0 ? solutions : ['Run cordova clean && cordova build android'],
        recommendedSteps: [
          'Run "cordova requirements android" to check dependencies',
          'Update platform: "cordova platform rm android && cordova platform add android@latest"', 
          'Clean build: "cordova clean && cordova build android"',
          'Check AndroidManifest.xml for missing android:exported attributes'
        ]
      };
    },
  });

  agent.addSkill({
    name: 'IOSSigningHelper',
    description: 'Configure iOS code signing certificates and provisioning profiles', 
    process: async ({ certificateType, bundleId, teamId }) => {
      const buildJsonConfig = {
        ios: {
          [certificateType === 'distribution' ? 'release' : 'debug']: {
            codeSignIdentity: `iPhone ${certificateType === 'distribution' ? 'Distribution' : 'Developer'}`,
            developmentTeam: teamId || 'YOUR_TEAM_ID',
            packageType: certificateType === 'adhoc' ? 'ad-hoc' : 
                        certificateType === 'distribution' ? 'app-store' : 'development',
            provisioningProfile: 'AUTO'
          }
        }
      };

      return {
        certificateType,
        bundleId,
        buildConfig: buildJsonConfig,
        instructions: [
          'Open Xcode → Preferences → Accounts',
          `Add Apple ID and select team: ${teamId || 'YOUR_TEAM_ID'}`,
          `Download ${certificateType} certificates`,
          `Create ${certificateType} provisioning profile for ${bundleId}`,
          'Save the build.json configuration in your project root',
          `Build with: cordova build ios --${certificateType === 'distribution' ? 'release' : 'debug'} --device`
        ]
      };
    },
  });

  console.log('✅ Mobile DevOps Agent initialized with 3 specialized skills!');

  // Test all skills without API calls
  console.log('\n📱 Testing Cordova Config Generation...');
  const configResult = await agent.call('CordovaConfigGenerator', {
    appName: 'SmythOS Mobile Demo',
    packageId: 'com.smythos.mobile.demo', 
    platforms: ['android', 'ios'],
    minSdkVersion: 24
  });
  console.log('Generated Config Features:', configResult.features);

  console.log('\n🔧 Testing Android Build Diagnostic...');
  const diagnosticResult = await agent.call('AndroidBuildDiagnostic', {
    errorLog: 'AAPT: error: resource android:attr/lStar not found. Could not find method compile() for arguments',
    targetSdkVersion: 35
  });
  console.log('Diagnosis:', diagnosticResult.diagnosis);
  console.log('Solutions:', diagnosticResult.solutions);

  console.log('\n🍎 Testing iOS Signing Helper...');
  const signingResult = await agent.call('IOSSigningHelper', {
    certificateType: 'distribution',
    bundleId: 'com.smythos.mobile.demo',
    teamId: 'ABCD123456'
  });
  console.log('Build Config:', JSON.stringify(signingResult.buildConfig, null, 2));

  console.log('\n🎯 Mobile DevOps MCP Server ready for SmythOS integration!');
}

main().catch((error) => {
  console.error('❌ Error:', error);
  process.exit(1);
});
